### ISSUE TITLE
Non-AK for Lab 4 is missing Ex 4 Task 5

### ISSUE THREAD

**Issue by MikeBazMSFT** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#100]
## Location

- Course: 203L04
- Exercise: 4
- Task: 5
- Step[s]: n/a

## Description

The non-answer-key version of Lab 4 Exercise 4 is missing task 5.  That task is present in the answer key version.

## Repro steps

n/a

**Comment by seesharprun** [comment]
This task was removed by design.
