### ISSUE TITLE
Friendly lab page refers to "modules" when they really aren't

### ISSUE THREAD

**Issue by MikeBazMSFT** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#101]
## Location

https://microsoftlearning.github.io/AZ-203-DevelopingSolutionsforMicrosoftAzure/

## Description

The "friendly" lab list page is very useful and helpful.  However, it does refer to each book (course?) as a "module," which is a little confusing given that "module" actually has a meaning as a subset of a book.

**Comment by seesharprun** [comment]
I updated the website with the appropriate "course" headings. You may need to Ctrl+F5 to see them.
