### ISSUE TITLE
Mis-numbered steps in AZ-203t03 lab

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#103]
## Location

- Course: AZ-203t03
- Exercise: 04
- Task: 03
- Step[s]: 00

## Description

Task 3 is missing. (miss numbered ?)

There are tasks 1,2,4,5,6,7

## Repro steps

1.
1.
1.

**Comment by seesharprun** [comment]
Resolved in latest version of lab instructions
