### ISSUE TITLE
Expensive default Database Gen 5 2 vCores

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#104]
## Location

- Course: az-203T03
- Exercise: 2
- Task: 3 import SQL Database
- Step[s]: 00

## Description
Select Default Database

Description of issue
Default Database isn't a Basic SQL Database anymore. Now, the default is Gen 5 2 vCores. Estimated Costs of more than 300 dollars (instead of 4 a month).

## Repro steps

1. Select poysqlsrvr*
1. Import Database
1. Select Storage Account
1. Select Pricing Tier

**Comment by seesharprun** [comment]
There's a bit to explain here so I will try my best to break this down:

- Yes, the new instructions tell you to leave the pricing tier set to the new default value:
    - General Purpose tier
    - Pre-provisioned throughput
    - Gen 5 hardware
    - 2 vCores
    - 32 GB maximum data size
- The new pricing tiers are recommended over the legacy pricing tiers
- We considered having students switch to Serverless SQL database, but we found the performance lacking during testing of the lab instructions.
- The old default size (Basic) is still available in the interface if you wish to select that size. 
- The new default size does cost more than the old Basic size
    - The new size would cost $231.28 USD if you left it running 24/7 for an entire month.
    - The lab is scheduled to run for 90 minutes with the students deleting their resource group at the end of the lab. If a student completes the lab within the allocated time, they should expect no more than a $1 of consumption to be used by the service instance.
    - If a student forgot to delete the resource group, then it is possible for the SQL database to use up all of their Azure Pass credits. It would take ~200 hours to burn through all of their credits. This is longer than the week that is typically prescribed to deliver this series of courses
- We try to design the lab instructions to use as many default settings as possible. In practice, it can be confusing to jump between 2-4 blades just to create a single resource. When writing the lab instructions, the design goal is to minimize unnecessary clicking.
- As a MCT, you can always demonstrate how to "switch back" to the legacy tiers and set your SQL database to the Basic tier.

**Comment by molenaar** [comment]
Thanks for the info.
