### ISSUE TITLE
Azure UI Changes

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#105]
## Location
https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-203_02_lab_ak.md
- Course: Lab: Building a web application on Azure Platform-as-a-Service offerings
- Exercise: 03
- Task: 01
- Step[s]: 06:

viii In the Storage section, select Use existing, and then select the imgstor* storage account you created earlier in this lab.

ix Leave the Application Insights field set to its default value.

x Select Create.

## Description 

Directions are outdated with azure.  

Description of issue

Instructor has advised the following suggestions:

Exercise 3 Task 1 Step 6. vii has wrong tab. 
Click the Hosting tab. In the Storage section, select Use existing, and then select the imgstor* storage account you created earlier in this lab. 
Exercise 3 Task 1 Step 6. ix has wrong tab. 
Click the Monitoring tab. Leave the Application Insights field set to its default value. 
Exercise 3 Task 1 Step 6. x 
change "Select Create" to "Select Review and Create and then select Create". 

![image](https://user-images.githubusercontent.com/41710326/70443547-f735cb80-1a5d-11ea-91c9-6760ebc6c7af.png)

As a side note, they also advised the file pathing has (F): and if possible would like to see F:.  

Thank you!

**Comment by seesharprun** [comment]
It looks like those steps were updated in AZ-203-T04 but not AZ-203-T02. This was corrected in commit 4c781433f5f30039ec20d4de01db451e0440023e and the latest version of the lab instructions.

We also keep the AllFiles to (F): to match the way it is done in other MOC instructions.
