### ISSUE TITLE
Linux is default App Service Plan 

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#106]
## Location

- Course: AZ-203T02
- Exercise: All
- Task: 00
- Step[s]: 00

## Description
Linux is the default App Service Plan option.

Description of issue
When you create an Web App, it created a default Service Plan based on Linux. A student created a Api following the instructions and ended up with a Linux Service Plan. After that creating a Web App based on windows gives an error because you cannot add both linux and windows service plans in the same resource group.

Changing this default is a little bit strange....

However reproducing the steps, I end up with a Windows Service plan.

## Repro steps

1.
1.
1.

**Comment by seesharprun** [comment]
This lab has been updated to use a Linux App Service Plan
