### ISSUE TITLE
[Lab upgrade request] Azure Functions V3

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#108]
It's not a bug, its update request. My students asked me yeasterday- let's use latest version of Microsoft technologies for this course.

## Location
https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-203_02_lab.md
https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/blob/master/Allfiles/Labs/02/Starter/function.proj

- Course: 00
- Exercise: 3
- Task: 1

## Description
Microsoft recently make Azure Functions V3 GA. It will be nice to update in a future lab files to use .net core 3.1 and Azure Functions v3 as a latest and greatest technologies. 

https://dev.to/azure/develop-azure-functions-using-net-core-3-0-gcm

**Comment by seesharprun** [comment]
This will be implemented in the upcoming release of AZ203.

Please refer to the course schedule on MCT central for a release date.
