### ISSUE TITLE
Lab 1 problem with single hyphens and quotes

### ISSUE THREAD

**Issue by tinodo** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#127]
In Lab 1 we need to issue the dotnet new console command.
It's listed in the documentation with "-output" and "-name" parameters.

This should either be "--output"  and "--name" or "-o" and "-n".

Single hyphen with full name does not work.

The same applies to some az commands in the lab.
A hint is made towards "az --help" but once formatted in the lab manual, it reads "-help" which doesn't work. (Use either -h or --help)

Last, we see jmespath queries in AZ commands, like this:

az vm list-ip-addresses --resource-group ContainerCompute --name quickvm --query '[].{ip:virtualMachine.network.publicIpAddresses[0].ipAddress}' --output tsv

This is acceptable on some platforms, but not on others. Why not just omit them? Then it works on all platforms. E.g.

az vm list-ip-addresses --resource-group ContainerCompute --name quickvm --query [].{ip:virtualMachine.network.publicIpAddresses[0].ipAddress} --output tsv

Thanks!

Tino

**Comment by seesharprun** [comment]
I am going to address each issue with a separate comment so we can thread this easier.

**Comment by seesharprun** [comment]
The source Markdown files and the produced Word documents all correctly contain double hyphens so there's no issue with the source code.

However, the website that is produced incorrectly combines the two hyphens if the command is spelled out in plain text. I can fix that in the high-level instructions by changing the instruction to:

> Use the **dotnet new** command to create a new .NET Core console application named **ipcheck** in the current directory.

And leave the full command in the lab answer key where it is rendered correctly.

**Comment by seesharprun** [comment]
As far as query quotes. They are required in some cases.

For example, the following command will have a bash syntax error in the Azure Cloud Shell:
```
az acr list --query max_by([], &creationDate).name --output tsv
```

But this command works:
```
az acr list --query 'max_by([], &creationDate).name' --output tsv
```

**Comment by seesharprun** [comment]
I resolved the rendering bug in the web-based instructions that you mentioned. Please reopen this issue if the fix doesn't resolve your issue.
