### ISSUE TITLE
Lab 2 - .NET 2.2 removed from Azure Portal selection

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#130]
The lab includes the following step:

> In the Runtime stack section, select .NET Core 2.2.

This version has been recently removed by Microsoft. The versions currently available are in the following screenshot. My students picked 2.1 LTS as a workaround and it worked fine thus far.

![image](https://user-images.githubusercontent.com/1765732/74274376-07795980-4ce0-11ea-871a-66adc29b2fa0.png)

Please update this lab and any similarly-impacted subsequent labs as appropriate.

**Comment by seesharprun** [comment]
You are correct, .NET Core 2.2 is now out of support so we fell back to .NET Core 2.1 LTS. The next course's labs will use .NET Core 3.1 LTS

**Comment by VitalyMCT** [comment]
Thanks for your super-fast processing of this issue @seesharprun . Much appreciated!
