### ISSUE TITLE
A note about lab machine sign in instructions in LAKs

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#132]
The LAKs contain the following note:

> Note: Lab virtual machine sign in instructions will be provided to you by your instructor.

However, the previous paragraph actually contains the sign-in instructions. I believe this note should thus be removed.

**Comment by seesharprun** [comment]
These instructions are referring to how to sign-in to the ALH lab environment (MLO, etc.).

Students will get those instructions from their trainer.

Is there a better way to describe this?

**Comment by VitalyMCT** [comment]
Got it. Perhaps we can replace "sign in" with "connect" then? Just to differentiate from the reference to "sign in" in the previous paragraph. Something like this:

> Note: Instructions for connecting to the lab virtual machine will be provided by your instructor.

**Comment by seesharprun** [comment]
How about:

> **Instructions**: Instructions to connect to the virtual lab environment will be provided by your instructor.

**Comment by VitalyMCT** [comment]
Looks great to me!
