### ISSUE TITLE
Error executing git cloning step

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#134]
The following step fails on the standard lab VM image:

> git clone --depth 1 --no-checkout https://github.com/microsoftlearning/AZ-203-DevelopingSolutionsForMicrosoftAzure .

LODS advised this is due to presence of System Volume Information on the root of drive F:

Proposal: update instructions to clone the files into a (newly created) empty subfolder.

**Comment by seesharprun** [comment]
The official lab VMs were tested and work correctly with the cloning instructions. This seems to be an issue with the way LODS implements their VMs. This issue would need to be filed with them directly.
