### ISSUE TITLE
Lab 6, Exercise 3, Step 8

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#135]
The Products field referenced here is no longer available on this screen. We should either remove this step or request students to make the product selection from the dedicated Products blade after the API is created.

**Comment by simonech** [comment]
In consumption plan, the products are not created. Easy fix is ask to create with normal tier :) 
In consumption also the echo api is not created.

**Comment by seesharprun** [comment]
Resolved by #138
