### ISSUE TITLE
Bug in referenced Cosmos DB Lib

### ISSUE THREAD

**Issue by derhoppe** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#136]
## Location

- Course: AZ-203T03
- Exercise: 04
- Task: 01
- Step[s]: 07

## Description

Description of issue

> In the command prompt, enter the following command and press Enter to import version 3.0.0 of the Microsoft.Azure.Cosmos from NuGet:
> 
> dotnet add package Microsoft.Azure.Cosmos --version 3.0.0

Should be changed to version 3.1.0 
Oherwise the price values will be displayed as millions. Decimals are pulled incorrectly in version 3.0.0

**Comment by seesharprun** [comment]
Upgraded **Microsoft.Azure.Cosmos** to **3.7.0**.
