### ISSUE TITLE
InitializeAsync method in Lab 3 starter files has incorrect signature

### ISSUE THREAD

**Issue by DarrellWire** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#16]
public async Task InitializeAsync(EventsContext eventsContext)
        {}
is referenced by var task = new ContextInitializer().InitializeAsync(eventsContext, registrationContext);

the inclusion of the registrationContext appear to be in error

**Comment by seesharprun** [comment]
Resolved in [Version 20190701.10](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190701.10).

Updated invocation of InitializeAsync().
