### ISSUE TITLE
How can I connect to the windows 10 virtual machine as below?

### ISSUE THREAD

**Issue by kiriejs** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#2]
How can I connet to the windows 10 virtual machine in the instruction as below?

Sign in to the lab virtual machine
Ensure that you are signed in to your Windows 10 virtual machine by using the following credentials:
Username: Admin
Password: Pa55w.rd

**Comment by seesharprun** [comment]
The lab virtual machine will be on the Learning Download Center on or before the course release date. You can refer to the MOC Title Plan for an exact release date.

**Comment by vitaly-livshits** [comment]
According to Courseware Title Plan this course was released on March 29th. 

Where to find the instructions for using ALHs with it? 

I've gone through all the files in LDC and in this repo and was unable to find such instructions.

Thanks,
Vitaly

**Comment by seesharprun** [comment]
I have never done an ALH class before myself so I imagine that you could get those instructions on the MCT forums or the Couseware support channel.

**Comment by vitaly-livshits** [comment]
Yes, I've never done an ALH class either. Many (most?) MCTs are in the same boat. We are used to having VM images available in LDC.

It is precisely for this reason - i.e. a new process for doing labs - that Microsoft and/or the course authors should publish clear instructions about using ALHs. These instructions should be linked to from this repo and from the instructor guide documents. 

Labs are crucial to successful ILT delivery. MCTs should be able to guide students through them without opening extra support tickets and without guessing about the proper approach.

Is Microsoft personnel or AZ-203 course vendor monitoring this repo?

**Comment by seesharprun** [comment]
Yes, this repository is monitored by the course owner/author who is a Microsoft employee.

**Comment by vitaly-livshits** [comment]
Would you mind tagging that person in this thread so we get an answer?

**Comment by seesharprun** [comment]
@JeffKoMS

**Comment by JeffKoMS** [comment]
@vitaly-livshits Microsoft made the change to the ALH solution at the end of 2018 for new courses, and you should see ALH options when purchasing a course and in the Courseware Marketplace. I've let some others internally know that we seem to have a few MCTs struggling with this change and that we may need to come up with some how-to's to help them along. Thanks for the feedback.

**Comment by vitaly-livshits** [comment]
@JeffKoMS, I've just added all 6 AZ-203 courses to Skillpipe bookshelf a few days ago. 

There was no option related to ALH. Do you know for a fact that it's supposed to appear in Courseware Marketplace? If so, can you please provide specific instructions on where to find it?

Here's the result of searching for AZ-203 in Courseware Marketplace:

![image](https://user-images.githubusercontent.com/1765732/56235398-5d945680-6055-11e9-949c-e5279d8e477e.png)

So yes, this would seem to be an important change that warrants detailed guidance from Microsoft. Something analogous to https://moc.microsoftlabsonline.com/static/mctreadiness_mlo_guide.pdf would seem appropriate here. Or at least a few paragraphs from someone in MSL explaining the new way to the MCT community. Right now we (AFAIK) have nothing and have to guess and scramble. Not very efficient!

Also, to confirm, are you saying this change to ALH-only is applicable to all new courses? There would be no VMs made available for self-hosting going forward? Does this apply to brand new courses only or to new versions of existing courses as well?

Thanks!

**Comment by ArmandoLacerda** [comment]
I've just ran this class last week and I created a Visual Studio 2017 Community Edition from the Market Place and done. The VM ate about $8 from their Azure subscription. And live as good from this perspective. 
The lab experience (lab instructions) were subpar.

**Comment by JeffKoMS** [comment]
Thanks for the feedback.
