### ISSUE TITLE
Lab 3, Ex 5, Step 3 - Run() method signature

### ISSUE THREAD

**Issue by ChrisBarkerMCT** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#20]
# Module: 03
#### Step: 03

There is no signature for a Run() method in the `ProcessDocuments` class; neither is there any instances of some of the method parameters in the entire solution.

Repro steps:

1. Open `ProcessDocuments.cs`
1. Locate the Run() method with the following signature `public static async Task Run(Stream input, string name, Stream output, TraceWriter log)`
1. Cannot locate a Run() method with the signature

**Comment by rjankathi** [comment]
Able to locate the Run Method (check this link  https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-203_03_lab.md it has better instructions than the answer key AZ-203_03_lab_ak.md instructions ).

**Comment by ChrisBarkerMCT** [comment]
Thanks for that, you are correct indeed! 😊
It would be nice if the "ak" file had the "answer key" or detail steps and the main file has high level instructions as is what the convention is for labs from MSL. 🤔

**Comment by JeffKoMS** [comment]
The "ak" files do include much more detailed steps than the main file - which is much more high level. That's why the main file for lab 3 is 665 lines long and the "ak" file is 1011. Errors in the labs are being addressed and we hope to have everything sorted shortly.
