### ISSUE TITLE
In Task 2 use Azure CLI Command, step number 9 it should be $ipAddress

### ISSUE THREAD

**Issue by bhaskar247** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#21]
# Module: 00
#### Step: 00

Description of issue
In Task 2 use Azure CLI Command, step number 9 it should be $ipAddress
ipAddress=$(az vm list-ip-addresses --resource-group ContainerCompute --name quickvm --query '[].{ip:virtualMachine.network.publicIpAddresses[0].ipAddress}' --output tsv)
 
but it should be 
$ipAddress=$(az vm list-ip-addresses --resource-group ContainerCompute --name quickvm --query '[].{ip:virtualMachine.network.publicIpAddresses[0].ipAddress}' --output tsv)
 
Repro steps:

1.
1.
1.

**Comment by seesharprun** [comment]
Resolved in [Version 20190701.04](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190701.04). The code that follows best practices was:

```
ipAddress=$(az vm list-ip-addresses --resource-group ContainerCompute --name quickvm --query '[].{ip:virtualMachine.network.publicIpAddresses[0].ipAddress}' --output tsv)
```
