### ISSUE TITLE
Can't create API App / Doesn't work as described

### ISSUE THREAD

**Issue by willnix86** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#24]
# Module: AZ203
#### Step: 1

Description of issue
I don't see how to build an Api app in Azure. I can build webapps / function apps / app servers, but nothing just as simple as listed in Task 4. I tried to follow the steps adjusting to using a webapp, but then no GET request brings me back the JSON described I just get taken to a Kudu console.

Repro steps:

1. Login to Azure Portal with a trial/free account
2. Follow the steps in the lab

**Comment by JeffKoMS** [comment]
@willnix86 I'm not quite following what you're saying above. Did you follow the steps in Task 4 but didn't see API App in the marketplace so you chose Web App? Or, did you follow the steps and chose API App but the rest of the lab didn't work for you?

**Comment by willnix86** [comment]
Sorry, I meant that I followed the steps in the lab but didn’t see API App as an option in the marketplace.

**Comment by JeffKoMS** [comment]
Thanks for clarifying. Looks like that was a change made in the portal in the last few weeks. We'll hopefully get some updated instructions available shortly.

**Comment by willnix86** [comment]
That would explain it!! Thanks for looking into it. The labs are super helpful!!

**Comment by SychevIgor** [comment]
@JeffKoMS  - will be nice to have this new guide... I will present this module today on my training.

**Comment by SychevIgor** [comment]
The same problem with Module 5 Lab5 where used API Apps.
![image](https://user-images.githubusercontent.com/578954/60381981-08b58900-9a65-11e9-8be0-3d0d2bf005e1.png)

**Comment by seesharprun** [comment]
@willnix86 I just followed the Answer Key steps in Task 4 below:

1.  In the left navigation pane of the portal, select **+ Create a resource**.

1.  At the top of the **New** blade, locate the **Search the Marketplace** field.

1.  In the search field, enter **API** and press Enter.

1.  In the **Everything** search results blade, select the **API App** result.

I saw **API App** in the list of results. Are you saying you don't see this option?

![image](https://user-images.githubusercontent.com/5067401/60447743-13515900-9bf2-11e9-8f36-3f0e79d2e31b.png)

I was able to complete the lab using an API App.

**Comment by seesharprun** [comment]
@SychevIgor the steps were written from the perspective that you are using an API App resource. The lab steps would be incorrect if you are using a Web App resource. In your screenshot, you are creating a Web App.

**Comment by seesharprun** [comment]
Closed due to no-repro. Please re-open if the screenshot doesn't solve your issue.

**Comment by SychevIgor** [comment]
Looks like it was a bug in Azure portal it self. Now I can find it. @seesharprun

**Comment by SychevIgor** [comment]
@seesharprun may we at least update for mod module 5 lab 5 (see previous screenshot) text https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/issues/24#issuecomment-506941317
because text on a portal is a bit different from what was in a guide
![image](https://user-images.githubusercontent.com/578954/60452251-d0fe3b00-9c36-11e9-95a9-31f93857837d.png)
