### ISSUE TITLE
ACR enable/disable button

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#28]
# Module: 01
## Lab: 01
Ex 4
#### Step: 3
https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-203_01_lab.md

On a latest Azure portal, there is no "update button". It will be auto-saved. Please update guide to address it 
![image](https://user-images.githubusercontent.com/578954/60170275-cc89ea80-9810-11e9-92ca-660975de3027.png)

**Comment by seesharprun** [comment]
This is resolved in [Version 20190701.07](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190701.07).
