### ISSUE TITLE
[Lab request] M3, L3, Ex3, Task1,2 sql db initialization 

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#30]
# Module: 3
## Lab/Demo: Labs\03\Starter
###Exercise 3:
### Task: 1,2

Between task 1 and task 2 we do not run our application, but changed one methods twice. It's strange, when we are rewriting one code twice without even running it. 
I guess, we can drop code from task 1 and use code from task 2 directly without extra steps.
![image](https://user-images.githubusercontent.com/578954/60248467-61511e80-98cb-11e9-908b-7433bf574acd.png)
![image](https://user-images.githubusercontent.com/578954/60248561-952c4400-98cb-11e9-8386-67fcd1bdb110.png)

**Comment by seesharprun** [comment]
This is a request to add a new exercise to build the code. This was discussed in #6 before that issue was closed. The course author/owner (@JeffKoMS) should review this issue to determine if new content is appropriate.

**Comment by JeffKoMS** [comment]
Hi, thanks for the feedback. This looks like it may be a straightforward addition. I'll see if we can get this change implemented soon.

**Comment by SychevIgor** [comment]
@seesharprun @JeffKoMS to be fair- it's not a new exercise. it's request to update existing one.
My students didn't find sense to twice update the same code without even running an app. mechanical copy-paste - it's not what they expect.

**Comment by JeffKoMS** [comment]
Yep, not seeing it as a new exercise just a fairly straightforward addition. We're on the same page.
