### ISSUE TITLE
[Lab request] M3, L3, Ex5-6 verification between exercise 

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#31]
# Module: 3
## Lab/Demo: 3
###Exercise 5 and 6:

As a last step in ex5 we should add some step when we should run an app an check that it's working.
Otherwise we are rewriting one code twice without verification that it's work
![image](https://user-images.githubusercontent.com/578954/60249196-f7d20f80-98cc-11e9-87fd-66e14de2dbe9.png)

**Comment by seesharprun** [comment]
This is a request to add a new exercise to build the code. This was discussed in #6 before that issue was closed. The course author/owner (@JeffKoMS) should review this issue to determine if new content is appropriate.

**Comment by JeffKoMS** [comment]
Same thing here as your other suggestion @SychevIgor. We'll evaluate shortly and see if we can get changes implemented soon.
