### ISSUE TITLE
No reference for ProcessStorageMessage() method in AZ-203_03_lab_a Exercise 5: Authoring Azure SDK code to connect to Azure Storage

### ISSUE THREAD

**Issue by rjankathi** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#32]
# Module: 03 Develop for Azure Storage
##### Step: 1

Description of issue
In Exercise 5:  Authoring Azure SDK code to connect to Azure Storage there's no reference for ProcessStorageMessage() method
Repro steps:
1. Goto to Exercise 5 Authoring Azure SDK code to connect to Azure Storage 
 --Task 1: Implement a blob trigger and output for Azure Functions

**Comment by seesharprun** [comment]
Resolved in [Version 20190701.10](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190701.10).

Added ProcessStorageMessage minimal implementation.
