### ISSUE TITLE
[Lab Request] AKS/Kubernetes

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#34]
# Module: 01
For Module 1- "Develop Azure Infrastructure as a Service compute solutions", we require some lab that will cover AKS and Kubernetes, because current Lab not covering this topic from the exam.

https://www.microsoft.com/en-us/learning/exam-az-203.aspx
"create an Azure Managed Kubernetes Service (AKS) cluster
create container" (C)

**Comment by JeffKoMS** [comment]
Thanks for the feedback. We're going to evaluate updating the labs across all the AZ-203 courses in the near future to include more module-specific labs.

**Comment by tiagocostapt** [comment]
@JeffKoMS that would be awesome!!! We need lab specific labs. I had to build some of myself or else students don't get ready for the exam.
