### ISSUE TITLE
[Lab Request] Azure Batch Services

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#35]
# Module: 01
For Module 1 (Develop Azure Infrastructure as a Service compute solutions), we require some lab that will cover Azure Batch Services, because current Lab not covering this topic from the exam.

https://www.microsoft.com/en-us/learning/exam-az-203.aspx
"**Implement batch jobs by using Azure Batch Services**
- manage batch jobs by using Batch Service API
- run a batch job by using Azure CLI, Azure portal, and other tools
- write code to run an Azure Batch Services batch job
" (C)

**Comment by JeffKoMS** [comment]
Thanks for the feedback. We're going to evaluate updating the labs across all the AZ-203 courses in the near future to include more module-specific labs.  We're also making some of the content that could be used for demonstrations easier to spot so some of these could be covered by those.
