### ISSUE TITLE
[Lab Request] Azure Mobile App 

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#36]
# Module: 02
For Module 2 (Develop Azure Platform as a Service compute solutions), we require some lab that will cover next set of feature from Mobile Apps:

"Create Azure App Service mobile apps
- add push notifications for mobile apps
- enable offline sync for mobile app
- implement a remote instrumentation strategy for mobile devices
" (C) https://www.microsoft.com/en-us/learning/exam-az-203.aspx

**Comment by JeffKoMS** [comment]
Thanks for the feedback. We're going to evaluate updating the labs across all the AZ-203 courses in the near future to include more module-specific labs.
