### ISSUE TITLE
[Lab Request] RBAC/CBAC

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#37]
# Module: 04

Lab for module 4 not covered significant part of content in the respective chapter of exam. We need a lab to cover RBAC/CBAC 

"**Implement access control**
- implement CBAC (Claims-Based Access Control) authorization
- implement RBAC (Role-Based Access Control) authorization
"

https://www.microsoft.com/en-us/learning/exam-az-203.aspx

**Comment by JeffKoMS** [comment]
Thanks for the feedback. We're going to evaluate updating the labs across all the AZ-203 courses in the near future to include more module-specific labs. These are good suggestions, thanks again.
