### ISSUE TITLE
Lab 5- highlight Load Test Deprecation date 31 of March 2020

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#38]
# Module: 5
## Lab: 4
Microsoft announced deprecated date for Load Tests in Azure DevOps, App Service and Application Insights https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol/
Agree, we still should know it for an exam https://www.microsoft.com/en-us/learning/exam-az-203.aspx "implement Application Insights Web Test and Alerts", but it will be nice to highlight in a guide- that it's just for an exam and it's not recommended for a new projects. 

Also, we can use this issue to later drop exercise 4 from lab 5 when Microsoft will remove feature from portals.

**Comment by seesharprun** [comment]
We are in a weird situation where this is required for the exam but deprecating in real life.

Let's keep this in the labs for now and then re-open this issue once the service is actually deprecated and removed from the exam objectives.

**Comment by SychevIgor** [comment]
It will be nice to push this question to MSFT, because the situation decreasing value from certification.

**Comment by seesharprun** [comment]
If you are looking for a change in the exam objectives, the best avenue for that would be in the MCT forums or the Training & Support forums. Members of the certification team wouldn't have visibility into the GitHub repository.
