### ISSUE TITLE
Application Insights "Application Type" property is no longer available on portal UX

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#39]
# Module: 5
### Task: 2

From Azure Portal removed for Application Insights property  "Application Type", but still exist in a guide. Please, actualize and fix it.

![image](https://user-images.githubusercontent.com/578954/60381907-3c43e380-9a64-11e9-9491-b842ee730102.png)
![image](https://user-images.githubusercontent.com/578954/60381913-4d8cf000-9a64-11e9-8cd7-b0aabe1ba9ab.png)

**Comment by seesharprun** [comment]
Removed Application Type step from instructions.

Resolved in [Verson 20190703.04](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190703.04).
