### ISSUE TITLE
Application Settings changed into Configuration

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#4]
# Module: 02
#### Step: 05

Description of issue
The Application Settings option is replaced by the new Configuration option. Appears in module 2 and perhaps in more labs.

Repro steps:

**Comment by seesharprun** [comment]
I believe this impacts the labs for **T02**, **T04** & **T05**

**Comment by SychevIgor** [comment]
Will be nice to fix it asap.

**Comment by seesharprun** [comment]
The fix for **T02** is resolved in [Version 20190701.08](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190701.08).

**T04** bug fix will be tracked in #44 

**T05** bug fix will be tracked in #43
