### ISSUE TITLE
Application Insights version in a guide is out dated

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#40]
# Module: 5
## Lab/Demo: 5
###EX 2
#### Task: 1

Currently avaliable v2.7.1. but looks like guide came from 70-532 exam and targeting 1.1.1 
Please, update the guide with modern version of app ins nuget package 
![image](https://user-images.githubusercontent.com/578954/60382053-2f27f400-9a66-11e9-8a33-b476c1606c61.png)

**Comment by SychevIgor** [comment]
The same problem with polly. v 1.1.0 it's 2013 year. Looks like authors of this guide used some time machine Current version is 7.1
https://www.nuget.org/packages/Polly 
![image](https://user-images.githubusercontent.com/578954/60382125-3e5b7180-9a67-11e9-94fe-b189666cc960.png)
![image](https://user-images.githubusercontent.com/578954/60382128-4a473380-9a67-11e9-958a-333a314c6c5e.png)

**Comment by seesharprun** [comment]
Updated the Polly and Application Insights packages to the latest current versions.

Resolved in [Verson 20190703.04](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190703.04).
