### ISSUE TITLE
Console or Web API apps in Lab5

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#41]
# Module: 5
### EX: 3

We have some error, because mentioned that we should create api app, but in a script is "console".
Please, actualize the text to address right type of an application. 
![image](https://user-images.githubusercontent.com/578954/60382079-c7be7400-9a66-11e9-86a3-01862293d352.png)

**Comment by seesharprun** [comment]
Updated title to reflect this is Lab 5, not 3.

**Comment by seesharprun** [comment]
Fixed the instructions to correctly specify .NET Console application.

Resolved in [Verson 20190703.04](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190703.04).
