### ISSUE TITLE
[Lab request] Events/Messaging

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#42]
# Module: 6
In Az-203 exam https://www.microsoft.com/en-us/learning/exam-az-203.aspx , part 6 covering multiple different messaging services, but in a lab guide we don't have any.
We 100% need a lab for modue 6 that will cover Service Bus, Event Hub, Event Grid, Storage Queue, Notification Hub.

Otherwise, course is not 1-1 covering az-203 exam

**Comment by JeffKoMS** [comment]
Thanks for the feedback. The goal of the labs is not to try and cover everything that is possibly covered on the exam - we'd end up with five days of labs. However, we are evaluating creating more labs and we'll definitely keep this as an option.
