### ISSUE TITLE
Student Handbook

### ISSUE THREAD

**Issue by vitaly-livshits** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#5]
The readme.md file in this repo has a few references to "student handbook". Can someone please explain exactly what that is in the context of AZ-203? 

The associated download link takes us to labs descriptions and allfiles folders. Is "student handbook" the same as lab descriptions?

Thanks,
Vitaly

**Comment by seesharprun** [comment]
Here’s a question I can field :smile:.

The student handbook refers to the collateral (lab instructions) that you will share with students to complete the labs. These are the DOCX files. In the past, it was sometimes referred to as “student material”.

You can always download the latest version of the handbooks by clicking the link at the top of the homepage of the repository. This takes you to the GitHub releases page. Each release contains a link to zip files with the Allfiles content and DOCX files.

**Comment by vitaly-livshits** [comment]
Thanks @seesharprun. So "student handbook" = lab instructions.

Are the instructions in Word files automatically synced up with the ones in the zip files and with the ones in GitHub Pages? I.e. is the content in all 3 versions always the same?

I am new to this, however, it seems to me that the GitHub Pages version (https://microsoftlearning.github.io/AZ-203-DevelopingSolutionsforMicrosoftAzure/) is easiest for the students to reference. There is no need to download anything and the syntax highlighting (in JSON, PowerShell, etc.) makes the code easier to read.

**Comment by seesharprun** [comment]
They are synced up with a very small delay. Anytime the GitHub markdown (in the master branch) is updated, GitHub.com automatically builds the GitHub Pages website. This can take anywhere from 2-5 minutes. At the same time, Azure DevOps builds the DOCX files and creates a GitHub release. This can take anywhere from 5-10 minutes.

**Comment by vitaly-livshits** [comment]
Thanks! I really appreciate your prompt response on this one.
