### ISSUE TITLE
Lab 6, Ex 2, Task 3, Step 1 - Confuse description via Renewal

### ISSUE THREAD

**Issue by SystemOutCoding** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#51]
## Location

- Course: AZ203 Lab 06
- Exercise: 02
- Task: 03
- Step[s]: 01

## Description

Lab 6, Ex 2, Task 3, Step 1 - Confuse description of the Renewal(added)

## Repo steps
1.  In the **Import Data** blade, create a new indexer with the following details:
    
      - **Data Source**: Azure Table Storage
    
      - **Data Source Name**: tabledatasource
    
      - **Connection string**: \<*select the **prodstorage\*** storage account you created earlier in this lab\>*
    
      - **Table name**: products
    
      - **Index name**: products
    
      - **Key**: RowKey
    
      - Configure the index’s fields by using the table below:

        | **Field**    | **Type**   | **Retrievable** | **Filterable** | **Sortable** | **Facetable** | **Searchable** | **Analyzer**          |
        | ------------ | ---------- | --------------- | -------------- | ------------ | ------------- | -------------- | --------------------- |
        | **Key**      | Edm.String | **✓**           |                | **✓**        |               |                |                       |
        | **name**     | Edm.String | **✓**           |                | **✓**        |               | **✓**          | **Standard - Lucene** |
        | **price**    | Edm.Double | **✓**           | **✓**          | **✓**        | **✓**         |                |                       |
        | **quantity** | Edm.Int32  | **✓**           | **✓**          | **✓**        | **✓**         |                |                       |

        - **Indexer Name**: tableindexer

        - **Schedule**: Custom

        - **Interval**: 5

## Suggest Step

1.  In the **Import Data** blade, create a new indexer with the following details:

      1. At **Connect to your data** Tab

    
      - **Data Source**: Azure Table Storage
    
      - **Data Source Name**: tabledatasource
    
      - **Connection string**: \<*select the **prodstorage\*** storage account you created earlier in this lab\>*
    
      - **Table name**: products

      2. At **Customize target index** tab

      - **Index name**: products

      - **Key**: RowKey
    
      - Configure the index’s fields by using the table below:

        | **Field**    | **Type**   | **Retrievable** | **Filterable** | **Sortable** | **Facetable** | **Searchable** | **Analyzer**          |
        | ------------ | ---------- | --------------- | -------------- | ------------ | ------------- | -------------- | --------------------- |
        | **Key**      | Edm.String | **✓**           |                | **✓**        |               |                |                       |
        | **name**     | Edm.String | **✓**           |                | **✓**        |               | **✓**          | **Standard - Lucene** |
        | **price**    | Edm.Double | **✓**           | **✓**          | **✓**        | **✓**         |                |                       |
        | **quantity** | Edm.Int32  | **✓**           | **✓**          | **✓**        | **✓**         |                |                       |

        - **Indexer Name**: tableindexer

        - **Schedule**: Custom

        - **Interval**: 5

        - **Start Time UTC**: Default_(Required filed But can use Default)

### Screen Shot
1. tab_conn_your_data
![tab_connURdata](https://user-images.githubusercontent.com/22819926/61589191-85a9cd80-abe1-11e9-8e51-b400bdb18d75.PNG)

2. tab_create_an_indexer
![tab_createindexer](https://user-images.githubusercontent.com/22819926/61589192-85a9cd80-abe1-11e9-95b4-230eade1d91b.PNG)

**Comment by SystemOutCoding** [comment]
I gonna PR lab06.md && lab06_ak.md
:)

**Comment by seesharprun** [comment]
This has been fixed in both the high-level instructions and the answer key
