### ISSUE TITLE
AZ-203_03_lab is missing the instructions to build

### ISSUE THREAD

**Issue by NFGodoy** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#53]
## Location

- Course: AZ-300T03
- Exercise: 2 forward
- Task: 00
- Step[s]: 00

Starting with Exercise 2, students will be making changes to existing code but the project was never build. Deploying to Azure could be left, but running it locally seems to me an essential part of any kind of dev course. Otherwise it's a typing exercise.

Description of issue

## Repro steps

1.
1.
1.

**Comment by seesharprun** [comment]
We are working on the a new exercise in this lab that will have students build the lab and run it. You should expect that new exercise in the next couple of weeks.

**Comment by seesharprun** [comment]
The latest version of AZ-203T03 has a revamped lab where students are asked to build their project multiple times.

While it has gone through testing, this is a new release so I anticipate a couple of bugs here and there for the first few weeks.

**Comment by seesharprun** [comment]
The fix has been applied in [Version 20190812.12](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190812.12).
