### ISSUE TITLE
AzureB2C_AllowSQLS1Size

### ISSUE THREAD

**Issue by chavanagh** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#54]
## Location

- Course: AZ-203-DevelopingSolutionsforMicrosoftAzure 
- Exercise: AZ-203_03_lab
- Task: 02
- Step[s]: 12

## Description

"statusMessage": "{\"error\":{\"code\":\"InvalidTemplateDeployment\",\"message\":\"The template deployment failed because of policy violation. Please see details for more information.\",\"details\":[{\"code\":\"RequestDisallowedByPolicy\",\"target\":\"polysqlsrvrabhijit/polysqldb\",\"message\":\"Resource 'polysqlsrvrabhijit/polysqldb' was disallowed by policy. Policy identifiers: '[{\\\"policyAssignment\\\":{\\\"name\\\":\\\"AzureB2C\\\",\\\"id\\\":\\\"/subscriptions/ADD949ED-5364-4A5D-A78D-4C3607063182/providers/Microsoft.Authorization/policyAssignments/43c29111-5fab-420a-87ba-2f833b0f40eb\\\"},\\\"policyDefinition\\\":{\\\"name\\\":\\\"AzureB2C_AllowSQLS1Size\\\",\\\"id\\\":\\\"/subscriptions/ADD949ED-5364-4A5D-A78D-4C3607063182/providers/Microsoft.Authorization/policyDefinitions/AzureB2C_AllowSQLS1Size\\\"},\\\"policySetDefinition\\\":{\\\"name\\\":\\\"AzureB2C\\\",\\\"id\\\":\\\"/subscriptions/ADD949ED-5364-4A5D-A78D-4C3607063182/providers/Microsoft.Authorization/policySetDefinitions/AzureB2C\\\"}}]'.\",\"additionalInfo\":[{\"type\":\"PolicyViolation\"}]}]}}"

## Repro steps

1.
1.
1.

**Comment by seesharprun** [comment]
Did you perform this deployment in an Azure Pass subscription or a different Azure environment?

**Comment by chavanagh** [comment]
I am using the Microsoft Azure subscription provided by Simplilearn with a role as a Contributor
ID : add949ed-5364-4a5d-a78d-4c3607063182

**Comment by seesharprun** [comment]
That's an [Azure Policy](https://docs.microsoft.com/azure/governance/policy/overview) error indicating that the subscription they gave you access to does not have permission to create a SQL Database of size Standard (S1).

The labs are tested assuming that you are using the Azure Passes provided with the courses. You have two options:

- Switch to using an Azure Pass
- Have the administrator of the Azure subscription give you all of the permissions you need to create each resource in each of the labs. For example, you need permission to create a S1 size SQL database and that's disallowed by policy.

**Comment by seesharprun** [comment]
When you talk to your admin, have them lookup the ``AzureB2C_AllowSQLS1Size`` Azure Policy they have in effect.

**Comment by seesharprun** [comment]
I am closing the issue as learning partner's Azure policy is outside of the scope of lab support. If you think this is in error, you can re-open this issue.
