### ISSUE TITLE
Az203 - Lab 2 - Exercise 2 is broken

### ISSUE THREAD

**Issue by davidokeyode** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#55]
## Location

- Course: AZ203 (Lab 2)
- Exercise: 02
- Task: 03
- Step[s]: 15

## Description

The code seems to be broken. Deploying the application to an Azure Web App is successful but unable to browse to the app successfully. I get a HTTP 500 error message

## Repro steps

1. Complete the steps in this lab - https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-203_02_lab_ak.md
2. At Exercise 2, Task 3, Step 15, deployed the packaged application to the Azure Web App
3. Browse to the Azure WebApp. You get a HTTP 500 error. Debugging locally also gives a HTTP 500 error.

**Comment by seesharprun** [comment]
A HTTP 500 status indicates that there was something wrong with the server-side code.

When debugging locally, did you get a chance to look at the .NET exception message?

If so, could you share?

**Comment by seesharprun** [comment]
🏓 Just following up again on this

**Comment by seesharprun** [comment]
I'm closing the issue. If you are still experiencing the issue, simply re-open and I will be happy to look at this again.
