### ISSUE TITLE
AZ-203T04 - Lab referenced in PPT is missing

### ISSUE THREAD

**Issue by vitaly-livshits** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#57]
I thought to run this by the experts here. 

There is a lab reference on one of the slides in this course. It points to https://www.microsoft.com/handsonlabs/SelfPacedLabs and the lab is supposed to be called "Deploying services to secure secrets in Azure". However, no such lab exists at that site.

Any ideas?

![image](https://user-images.githubusercontent.com/1765732/62788169-5d044d80-ba94-11e9-9d82-89fbb41c9126.png)

**Comment by seesharprun** [comment]
@JeffKoMS, where did this slide come from? Was it a publishing error?

**Comment by adnkai** [comment]
The slides are from learningdownloadcenter.microsoft.com/.
The most recent slides refer to that lab, too. They were las modified on August 16th.

**Comment by seesharprun** [comment]
The latest revision of the lab slides has the Practice slide hidden (but not removed).

![image](https://user-images.githubusercontent.com/5067401/63390382-e2cda600-c37c-11e9-8aad-3b45a46c332b.png)

You can safely ignore this slide and it will be fully removed in the next version.
