### ISSUE TITLE
References to legacy course numbers in some of the labs instructions

### ISSUE THREAD

**Issue by vitaly-livshits** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#58]
One example is in screenshot below. Please review all instances and adjust accordingly.

![image](https://user-images.githubusercontent.com/1765732/62825495-a929bd80-bb7a-11e9-8e86-b754049a15f8.png)

**Comment by seesharprun** [comment]
Fixes are included in latest [Version 20190812.13](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190812.13).
