### ISSUE TITLE
Folder used in GitHub cloning instructions 

### ISSUE THREAD

**Issue by vitaly-livshits** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#59]
## Location

- Course: AZ-203
- Exercise: N/A, environment preparation
- Task: N/A, environment preparation
- Step[s]: N/A, environment preparation

## Description

The instructions say to clone to "Labfiles" folder, while the actual Git command clones to root of F: drive. Noticed in Module 3 lab and may apply to other labs as well.

Another minor item in the same step: "Microsoft" is missing from the project name in the instructions. The project name in the Git command is correct.

## Repro steps

![image](https://user-images.githubusercontent.com/1765732/62825551-bd21ef00-bb7b-11e9-8eb8-ec64425b231c.png)

**Comment by seesharprun** [comment]
Changed the text to say **Allfiles (F):\\** drive.

> Within the command prompt, enter the following command and press Enter to Clone the **microsoftlearning/AZ-203-DevelopingSolutionsForAzure** project hosted on GitHub into the **Allfiles (F):\\** drive:

Unfortunately, I couldn't find an example of where **Microsoft** was missing from the project name in the instructions. If you look at the line above the code sample, it says to clone the ``microsoftlearning/AZ-203-DevelopingSolutionsForAzure`` project which correctly includes the name.

Fixes are included in latest [Version 20190812.13](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190812.13).

**Comment by vitaly-livshits** [comment]
@seesharprun  My 2nd paragraph was about the project name referenced in the text of step #3.

It currently states "AZ-203-DevelopingSolutionsforAzure". The correct name is "AZ-203-DevelopingSolutionsfor**Microsoft**Azure".

**Comment by seesharprun** [comment]
Thanks for the clarification. I also fixed that and included it in [Version 20190812.14](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190812.14).

Since you are reviewing the course, keep an eye out for the new Lab #3. It's different than the past lab.
