### ISSUE TITLE
Evolving the Lab Environment

### ISSUE THREAD

**Issue by seesharprun** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#62]
There are a few major changes coming soon and I want to create an open discussion where we can discuss potential upgrades to the lab environment to help keep the labs current.

My goal is to turn this discussion into action items this fall.

Off the top of my head, I have a short list of things I would like to see:

- Move from .NET Core 2.2 to something newer
    - .NET Core 3.x should be GA soon. It’s very stable and introduces some C# language features that will make the lab code simpler to read.
    - .NET 5 is on the horizon. An alpha build is already available (https://github.com/dotnet/core-sdk) and I am personally using it on a daily basis
- Update Azure Storage Explorer
    - Needs an update
- Update Visual Studio Code
    - Also, needs an update
- Install [Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is)
    - This would be cool to use in a data lab
- Install dotnet tool [httprepl](https://github.com/aspnet/HttpRepl)
    - We can use this when we test the API app

**Comment by seesharprun** [comment]
There's a few more that I'm less sure on.

- Installing Docker
    - I don't see a way to do this and still keep the VM lightweight. Docker requires a fair amount of horsepower. For example, I have trouble running the SQL Docker container images on my Surface Book.
- Changing default browser to Edge Dev (Chromium)
    - This will solve a lot of portal UI bugs. Edge Dev is very stable already and is a good candidate.

**Comment by seesharprun** [comment]
Here's a new one

- Installing Windows Terminal (Preview)
    - This will make for a much better terminal environment
- Installing PowerShell 7
    - There's no reason to use the built-in PowerShell anymore

**Comment by seesharprun** [comment]
Let's talk about the preview services:

- PowerShell 7 is on it's second-to-last preview release (<https://devblogs.microsoft.com/powershell/powershell-7-preview-5/>). It's anticipated to be released in January.
- .NET Core 3.0 is in the wild and .NET Core 3.1 is expected to ship in December.
- Windows Terminal doesn't have a release date ☹️. I really want to see Windows Terminal make it into the next VM mostly because of accessibility issues. The terminal makes it easier to change default fonts and sizes while still allowing you to zoom using click+scroll. I think this will make it easier to use the terminal in the ALH interfaces or present as a MCT. Let's keep fingers crossed this RC or GAs before January.
- Edge Dev is another tool I am hoping gets a release before January. Since it's based on Chromium (and most web apps think it's Chrome), we are running into less portal bugs in testing. This would be a huge quality-of-life improvement for the lab environment.

As far as the length of some of the labs (I'm looking at you data lab), the feedback has been heard! The next iteration won't be nearly as long.

In the next course release, I will publish the list of software and versions installed on each VM and link to it from the readme on the home page of the repository.

**Comment by seesharprun** [comment]
The other thing brought to my intention was that 2.1 was the LTS version of .NET Core, not 2.2. 3.1 will be the next LTS version so I think we should shoot for that: <https://dotnet.microsoft.com/platform/support/policy>

**Comment by seesharprun** [comment]
I also saw Windows Terminal has an anticipated RC date in January and release in April. I'm ok with shipping the RC version in the VM.

**Comment by MikeBazMSFT** [comment]
An RC is probably good enough, especially for Windows Terminal, which at least for what we'd likely be doing will be sufficient.  You could in theory even use the Cloud Shell support in there, but that's so far very flaky and slightly confusing to use (since it's using the Device Login path) - so that support probably would be bad to leverage.

**Comment by seesharprun** [comment]
Believe it or not, writing instructions on how to login using the Device Code provider is much easier than the Interactive (browser-redirect based) provider.

**Comment by seesharprun** [comment]
I went and used my personal time machine 🚀 to find a list of software installed on the official VM.

For the next wave of labs, this list will be placed somewhere "official" in the Markdown content so it can be maintained properly.

For now, enjoy:

- Windows 10 
    - Recommend also installing Office 2016. 
- Latest version of Visual Studio Code (https://code.visualstudio.com/) with extensions:
    - Azure Account (https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account)
    - Azure Resource Manager Tools (https://marketplace.visualstudio.com/items?itemName=msazurermtools.azurerm-vscode-tools)
    - Azure CLI Tools (https://marketplace.visualstudio.com/items?itemName=ms-vscode.azurecli)
    - PowerShell (https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell)
    - C# (https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp)
- Latest version of Azure PowerShell (https://docs.microsoft.com/powershell/azure/install-az-ps)
- Latest version of Azure CLI (https://docs.microsoft.com/cli/azure/install-azure-cli)
- Latest version of Azure Storage Explorer (https://azure.microsoft.com/features/storage-explorer/)
- Git for Windows (https://git-scm.com/download/win)
- .NET Core 2.2 SDK (https://dotnet.microsoft.com/download) 
    - On the downloads page, select .NET Core 2.2 (not .NET Framework 4.7.2)
    - You want the SDK (to build applications), not the runtime

> Quick note: I highly recommend installing the preview Windows Terminal on your instructor machine. The terminal should now ship with the very good Cascadia Code font (https://github.com/microsoft/cascadia-code). The terminal supports the ability to zoom in and out using your scroll wheel and the shift key which makes it easier to demo scripts to students. The terminal also supports color schemes so you can implement a high-contrast theme to use in the terminal for environments where the project is not as well lit as you need.

**Comment by seesharprun** [comment]
Everyone's recommendations have been taken into consideration for the next version of the lab VM.

Thank you for your time!
