### ISSUE TITLE
Lab 06 - Create API Management earlier

### ISSUE THREAD

**Issue by vitaly-livshits** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#66]
As the instructions correctly mention, it may take Azure as long as 20-30 minutes to create the API Management resource. Proposal: move creation earlier in the lab so students do not need to wait to use the resource.

**Comment by seesharprun** [comment]
I’m 100% onboard with this suggestion

**Comment by seesharprun** [comment]
> I'm updating each of the open issues this week to let you know that there was a small delay in the latest round of updates. They should be ready about one week later than originally anticipated.

**Comment by seesharprun** [comment]
Creating the API Management service instance has been moved to be the first thing you do in Exercise 1.

Resolved in [Version 20190822.01](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190822.01).
