### ISSUE TITLE
Lab 5 Issues

### ISSUE THREAD

**Issue by j-ankur** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#69]
## Location

- Course: 05
- Exercise: 4
- Task: 01
- Step[s]: 08

## Description

When we run the load test it shows an error in the activity log. - "WRITE FAILED". Also the VSTS subscription doesn't gets created. I am experiencing this problem with Azure Sponsorship Subscription. However with MSDN Subscription it is working fine.

**Comment by seesharprun** [comment]
Where did you source your Azure Sponsorship Subscription?

I ask because we test the labs using Azure Passes and I want to validate if the issue is related to the sponsorship.

**Comment by Usamawahabkhan** [comment]
same issue

**Comment by seesharprun** [comment]
@Usamawahabkhan which Azure subscription are you using? Is it your MCT Azure subscription or an Azure Pass?

**Comment by seesharprun** [comment]
@j-ankur which Azure subscription are you using? Is it your MCT Azure subscription or an Azure Pass?

**Comment by Usamawahabkhan** [comment]
They used Pass sub. error wan an acrred on attendece subscription.

**Comment by seesharprun** [comment]
Thanks, we will look into the resource provider assignments on the Azure Pass and see what has changed.

**Comment by seesharprun** [comment]
Just pinging you to let you know that I didn't forget about your issue. There are some technical difficulties with obtaining Azure Passes right now.

**Comment by Usamawahabkhan** [comment]
Hi buddy, is their any ways next time I can be a part of this? When ms
learning start Session exam work items. I am listed with grand master.

**Comment by seesharprun** [comment]
@Usamawahabkhan, you should create a profile on [Microsoft Callobrate](https://aka.ms/collaborate) so you can be part of the pool of people considered when it's time to write exam items or update objectives.

**Comment by Usamawahabkhan** [comment]
i have created my Profile but it took me to Microsoft Partner Portal

**Comment by seesharprun** [comment]
We were unable to reproduce this issue using an Azure Pass. Please reopen if you experience this issue again with a screenshot of the error.
