### ISSUE TITLE
Unable to deploy web app to API App

### ISSUE THREAD

**Issue by krisrajzlive** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#72]
## AZ 203 Lab 2

- Course: AZ-203
- Exercise: 01
- Task: 06
- Step[s]: 16

## Unable to execute the command

The command failed to execute
az webapp deployment source config-zip --resource-group ManagedPlatform --src api.zip --name imgapikrisrajz
getting error message ResourceGroup could not be found though it exists (checked spelling, case everything seems mathcing).
Any help would be appreciated.
Thanks indeed.

## Repro steps

1.
1.
1.

**Comment by seesharprun** [comment]
What do you get when you run ``az group list``?

**Comment by krisrajzlive** [comment]
I am getting the message:
PS C:\Users\krisrajz\source\repos\MicrosoftLearning\AZ-203-DevelopingSolutionsforMicrosoftAzure\Allfiles\Labs\02\Starter\API> az webapp deployment source config-zip --resource-group ManagedPlatform --src api.zip --name imgapikrisrajz       
Getting scm site credentials for zip deployment
ResourceGroupNotFound - Resource group 'ManagedPlatform' could not be found.
PS C:\Users\krisrajz\source\repos\MicrosoftLearning\AZ-203-DevelopingSolutionsforMicrosoftAzure\Allfiles\Labs\02\Starter\API>  

All names are copied from AzurePortal.

**Comment by seesharprun** [comment]
Yes, but we need to verify that your Azure CLI instance is connected to the same subscription as you are seeing in the portal. Sometimes, your CLI can connect to a different default subscription.

Did you try ``az account show`` and ``az group list``?

**Comment by krisrajzlive** [comment]
Thanks Indeed for saving me and super quick response and making learning interesting! I appreciate.
I understood what has happened! I have two logins Enterprise and MSDN, some how az login takes only Enterprise and not my MSDN account which has everything I have. az account show, shows my Enterprise login details and not my MSDN.

**Comment by krisrajzlive** [comment]
I tried az login with tenantid and got this error message:
Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.
Not sure what next and how to proceed. Any further help would be much appreciated.

**Comment by krisrajzlive** [comment]
Looks like someone else has the same problem:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/f6ad2479-55d8-4c79-b585-ae27d72410a0/azure-xplatcli-cannot-login-due-to-wstrust?forum=azurescripting

**Comment by krisrajzlive** [comment]
Cool, this has helped me:
az account set --subscription "My Demos"

**Comment by seesharprun** [comment]
I'm glad you were able to work it out. Switching my account is something I have to do on a daily basis in the CLI.

It's a best practice to always run ``az account show`` and then ``az account set`` if you have multiple subscriptions.

For your students, they should have an Azure Pass and may be able to avoid this issue.
