### ISSUE TITLE
Preview not supported in /langversion

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#74]
## Location

- Course: AZ-203 Lab 03: Lab: Constructing a polyglot data solution
- Exercise: 04
- Task: 01
- Step[s]: 08

## Description

Description of issue

An instructor brought  to our attention the build failing for this step.  When I ran this lab, I too received the following error:

"Build FAILED.

CSC : error CS1617: Invalid option 'preview' for /langversion. Use '/langversion:?' to list supported values."

If I go to the Adventureworks.Migrate.csproj and remove preview from <LangVersion></LangVersion>, this builds successfully.  I attempted adjusting the Microsoft.Azure.Cosmos to version 3.1.0 after reading the following issues report: https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/issues/70 (in both the dotnet  add package and the .proj file) but I still received the above mentioned error.  

Does this have to do with some sort of outdated versioning or something else being missed? Thank you for your time.

**Comment by seesharprun** [comment]
Which lab host are you using for your virtual machine?

.NET Core 3.0 is in the wild so build issues will start to occur if anyone builds on a local machine.

**Comment by mreherefortea** [comment]
Thank you very much Sidney for looking into this, this is with Learn on Demand Systems.  The instructor was able to find a solution and advised the following:


Exercise 4 - Task 1 - Step 2
Instead of:
dotnet new console --name AdventureWorks.Migrate --langVersion preview

it should be:
dotnet new console --name AdventureWorks.Migrate --langVersion 7.1


Exercise 4 - Task 5 - Step 7
Instead of:
await Console.Out.WriteLineAsync($"Upserted document [Activity Id: {document.ActivityId}]");

the code should be:
await Console.Out.WriteLineAsync($"Upserted document #{++count:000} [Activity Id: {document.ActivityId}]");

**Comment by seesharprun** [comment]
I fixed this in the latest build of the course: [Version 20191008.07](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20191008.07).

Thanks for finding the fix! This was due to the release of a new version of C# and .NET Core 3.0.
