### ISSUE TITLE
 using blocks

### ISSUE THREAD

**Issue by Usamawahabkhan** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#77]
## Location

- Course: 203-4
- Exercise: 4
- Task: 2
- Step[s]: 7

## Description
7 Add two using blocks for the Microsoft.Azure.Storage and the Microsoft.Azure.Storage.Blob namespaces.

word blocks is confusing most student thing its 
usig block like 
Using (ClientContext cx = new ClientContext())
{
//do something here

}

Description of issue

## Repro steps

1.
1.
1.

**Comment by seesharprun** [comment]
What terminology should we use?

I checked <docs.com> and I saw three different terms:

1. The traditional using keyword along with a series of code expressions within curly braces is referred to as a [using statement](https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/using-statement):

    ```
    using (Type instance = new Type())
    {
        // Scoped logic
    }
    ```

1. The expressions at the top of a code file is referred to as a [using directive](https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/using-directive):

    ```
    using Namespace.Child;
    ```

1. The new expression syntax that was launched with C# 8 is called a [using declaration](https://docs.microsoft.com/dotnet/csharp/whats-new/csharp-8#using-declarations):

    ```
    using Type instance = new Type();
    // Scoped logic
    ```

**Comment by Usamawahabkhan** [comment]
"Using directive" to declare namespace

**Comment by Usamawahabkhan** [comment]
Is their any way we I can get connected with MS 203 content creation team.
I would like contribute as much as possible.

**Comment by seesharprun** [comment]
As far as courseware content is concerned, your best avenue to reach the authoring team is the MCT support forums. There is a special MOC Courseware section of the forum.

**Comment by seesharprun** [comment]
This has been resolved in the latest version of the lab [Version 20191013.03](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20191013.03).
