### ISSUE TITLE
Wrong instructions 

### ISSUE THREAD

**Issue by Usamawahabkhan** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#79]
## Location

- Course: 01
- Exercise: 04
- Task: 02
- Step[s]: 03

Is wrong "Deploy a new Azure Container Instance"
Option called now It should "Run Instance"

It make students quite confuse

## Description

Description of issue

## Repro steps

1.
1.
1.

**Comment by seesharprun** [comment]
It looks like the correct label is specified in the detailed lab instructions found in the answer key.

In the High-level lab instructions, it just asks the student to deploy a new ACI. It is up to the student to figure out which instruction will do that. If we just say “run instance”, students will not know what service to run an instance of (ACI, App Service, Kubernetes, VM, etc).

The high-level lab instructions purposefully leaves out detailed step-by-step instructions that are included in the answer key.

**Comment by Usamawahabkhan** [comment]
Thx
