### ISSUE TITLE
Demo instructions

### ISSUE THREAD

**Issue by vitaly-livshits** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#8]
Note: This ticket is regarding the .PPT slide decks in the LDC rather than the current contents of the repo on GitHub. Please advise if it should be posted elsewhere to get an authoritative response.

All 6 courses in the AZ-203 series have _very_ high level guidance for the instructor-led demos. This is very different from previous MOC courses, which had detailed demo instructions.

For example, the demo in AZ-203T05, Module 4, Lesson 1, states the following:

> Demo: Store cache values in Azure Cache for Redis
> 
> This revision of the course does not ship with demo instructions. For each demo, you will be given a list of specific tasks you should demonstrate to your students. The flow, content and structure of your demo is left to you to decide as an instructor.
>  
> In this demo, you should show students how to:
> Create a new Azure Cache for Redis instance
> Use the in-portal console to issue get and set commands to the Redis cluster

Are there plans to include demo instructions in subsequent releases of AZ-203? If so, how soon may we expect them to be added?

Thanks,
Vitaly

**Comment by JeffKoMS** [comment]
@vitaly-livshits Currently there are no plans to make the slides as highly detailed as they used to be. In Azure, things change so fast that it would be nearly impossible to ensure all of the details are technically accurate.
