### ISSUE TITLE
Lab 04 - Contents seems outdated

### ISSUE THREAD

**Issue by krisrajzlive** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#80]
https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-203_04_lab_ak.md

- Course: AZ-203, Lab04
- Exercise: 02
- Task: 02
- Step[s]: 06

## Description

I could not find many of those options hence could not complete

## Repro steps

1.
1.
1.

**Comment by seesharprun** [comment]
I will take a look at the portal to see if there has been any recent changes.

**Comment by seesharprun** [comment]
It looks like this part of the portal is unchanged. I have included a screenshot. My test team was unable to reproduce your bug.

![image](https://user-images.githubusercontent.com/5067401/69017561-dd7cf900-0975-11ea-8f14-da5daaee633b.png)
