### ISSUE TITLE
"Blobs" is now "Containers" in Storage UI

### ISSUE THREAD

**Issue by MikeBazMSFT** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#81]
## Location

- Course: AZ-203.2
- Exercise: 1; 3
- Task: 3; 4
- Step[s]: 2; 4, 5, 10

## Description

In the Azure Portal, for Storage, the "Blobs" view is the "Containers" view, as of about 3 weeks ago.  This likely impacts other labs as well but this is the first one where a student pointed it out to me.

## Repro steps

1. Navigate to a Storage Account
1. Notice under "Blob Service" the first option is now "Containers"

**Comment by seesharprun** [comment]
Resolved in latest version of labs
