### ISSUE TITLE
API URL needs protocol added

### ISSUE THREAD

**Issue by MikeBazMSFT** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#87]
## Location

- Course: 203.2
- Exercise: 2
- Task: 2
- Step[s]: 3

## Description

The Application Setting for the API URL needs the protocol to be included; the copied URL does not start with `https://` and the app fails with an unhelpful 503 failure without it.  There are two ways to approach this I think:

1. Change the lab instructions to tell the student to include `https://`

1. Change the web app to work either way to avoid the issue in any case

I think the second option is "better" although it's more work.

## Repro steps

1. Go through the lab - notice when you get to Exercise 2 Task 3 Step 20 the app does not work if you use the copied URL without "https://" in front.

**Comment by seesharprun** [comment]
Fixed in the latest version of the lab instructions.
