### ISSUE TITLE
Lab4 - Highlight that users should not use "Classic Functions app"

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#88]
## Location
- Exercise: 1
- Task: 4

## Description
Some of my students instead of following the guide and simply select "Function Apps", find that UX for Function apps is a bit different and contain separate tabs like "monitoring and hosting". They looks on Classic Function apps and find exactly the same set of settings as was in a guide and created Classic Function app. It was a mistake and after sometime they fixed it.
![image](https://user-images.githubusercontent.com/578954/67887649-c14b2080-fb5c-11e9-85e2-c2f39c870ce0.png)

Could you please highlight for such students, that the should use "non-classic functions apps" and maybe update the guide to address new "wizard" like experience where hosting and monitoring are separate tabs?

**Comment by seesharprun** [comment]
I'm holding off from changing the instructions because there was an issue yesterday with the Functions ARM template. None of my team could create a Function App at all. Once this issue is resolved (it seems like it is now), the instructions will be updated.

**Comment by seesharprun** [comment]
The creation instructions have been updated to resolve this bug.
