### ISSUE TITLE
Lab 5 code is wrong if .NET Core SDK 3.0 is installed

### ISSUE THREAD

**Issue by MikeBazMSFT** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#89]
## Location

- Course: 5
- Exercise: 2
- Task: 2
- Step[s]: 2

## Description

The ASP.NET WebAPI template has changed in .NET Core 3.0 from using `IWebHostBuilder` to `IHostBuilder.`  As a result, the code in the lab is not correct and the replacement code is not correct.

## Repro steps

1. ensure .NET Core SDK 3.0.0 is installed
1. Run the `dotnet new webapi --output . --name SimpleApi` command.
1. Observe the resulting `Program.cs` file.

## Proposed fix

If the empty project folder has a `global.json` with an appropriate SDK version (`2.2.x`), then everything works.  But we can't just drop one in the repo because we don't know what exact revision the user will have, unless we go back to some low enough revision that's 100% sure to be there.  So we could add steps to run `dotnet --info` and pick out the version or we could just put an old one in there.  All of this will have to be revisited as part of the discussed .NET Core update in issue #62

**Comment by seesharprun** [comment]
I will wonder aloud if we should postpone this fix until we release the version of the labs that supports .NET Core 3.x.

In it's current states, the labs are only supported on the official virtual machines hosted by ALHs and running .NET Core 2.x.

**Comment by MikeBazMSFT** [comment]
Hmm.  OK.  At least for my group of trainers, we commonly have people using local installs instead of the ALH VMs, because of terrible VM experience... so I feel like we at least need to document what's involved even though it's not officially supported.  So I propose that unless you have metrics around leaving issues open, we leave this open until the official move to 3.1 so that others can potentially see this info on the fix if they come look.

To be very specific on the "easiest" fix: 

1. Open a Terminal in Visual Studio Code.
2. Run `dotnet --listsdks`
3. Find the newest 2.x version on the list (the output will be sorted by order from oldest to newest)
4. In the root of your project folder, where you will be running the project creation, create a file named `global.json` with the following content:
```
{
    "sdk": {
        "version": "2.2.401"
    }
}
```
5. You can now run `dotnet new webapi --output . --name SimpleApi --force` (the `--force` handles the case of a student doing this against 3.0 without having to empty the folder first.)

**Comment by seesharprun** [comment]
I am ok with leaving this issue open

**Comment by seesharprun** [comment]
I left a comment in #62 where I included a list of software installed on the current lab VM. Much of that software is not used in the labs but it's useful to know exactly what you need.

If you have credits on your MCT Azure subscription, I recommend spinning up a Windows 10 1903 VM and installing the recommended software. You can setup the VM to automatically shutdown in the evening to preserve credits.

**Comment by MikeBazMSFT** [comment]
yeah that's fine for me, it's more students... although they could I guess build a jump machine themselves and go from there, or I could share out a custom image for them or something. 🤔  Maybe a custom template that I have them deploy if they want to, assuming they can RDP from their networks.

**Comment by seesharprun** [comment]
Officially the students should have lab environments provided by an ALH.

**Comment by seesharprun** [comment]
The next version of the lab instructions and VM will use .NET Core 3.0 making this a non-issue.

For now, I did include a Markdown file [lab.md](lab.md) that describes exactly what software is installed on the lab VM and supported for the current iteration of the labs.
