### ISSUE TITLE
Lab 4, Ex 4, Task 4 - 

### ISSUE THREAD

**Issue by mpaione** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#91]
## Location

- Course: AZ-293 T04
- Exercise: 4
- Task: 04
- Step[s]: 4

## Description

[Error] run.csx(4,23): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?)

## Repro steps

1. Performed all detailed steps
2. Save an Run ends with detailed compilation error
1.

**Comment by Grasher134** [comment]
Had the same issue today. All steps after this one are impossible to complete in Exercise 4

**Comment by seesharprun** [comment]
We are working hard to get this fixed ASAP. Some of the announcements at Ignite introduced breaking changes to the lab.

**Comment by seesharprun** [comment]
This was resolved in the latest update to the lab
