### ISSUE TITLE
photo gallery doesnt appear.

### ISSUE THREAD

**Issue by frankchienwang** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#92]
## Location

- Course: az 203
- Lab 2 ak
- Exercise: 02
- Task: 03
- Step[s]: 22

## Description

Contoso photo gallery doesnt show up.

Description of issue

Hi There.

Do you mind reviewing the second exercise? specifically when I hit step 22 I only get 500 errors, I dont get a "contoso photo gallery" of any sort.

Thanks!

**Comment by seesharprun** [comment]
Can you post a screenshot of the error message you are seeing?

**Comment by frankchienwang** [comment]
ah disregard please. My classmate pointed out I have the wrong url. Thanks for responding though.
