### ISSUE TITLE
Lab 5: Metrics in App Insights can't be observed for API project

### ISSUE THREAD

**Issue by megaromb** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#95]
## Location

- Course: 05
- Exercise: 2
- Task: 4
- Step[s]: 5

## Description

For a ASP.NET Core API project the metrics in Application Insights can't be observed because the app isn't configured to Azure metrics. 

Suggested Solution:
Set up the instrumentation key  (of the created Application Insight resource in Azure portal) in app settings, see "Enable Application Insights server-side telemetry (no Visual Studio)" (https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#enable-application-insights-server-side-telemetry-no-visual-studio)

## Repro steps

**Comment by seesharprun** [comment]
Yikes, it looks like a lab step was dropped as part of one of the edits.

The short-term fix is to pass in the **instrumentation key** as a string parameter to the ``services.AddApplicationInsightsTelemetry();`` line of code.

I'll get the lab instructions fixed as quickly as I can.

**Comment by seesharprun** [comment]
This is fixed in the latest version of the lab instructions.
