### ISSUE TITLE
Link broken: https://microsoftlearning.github.io/AZ-203-DevelopingSolutionsforMicrosoftAzure/

### ISSUE THREAD

**Issue by tinod** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#96]
The link to https://microsoftlearning.github.io/AZ-203-DevelopingSolutionsforMicrosoftAzure/ is broken. It appears as if this content was deleted.
Can you either upload the new content, or change the link in the readme.md?

**Comment by seesharprun** [comment]
The link is now fixed
