### ISSUE TITLE
"Solution" folder name can be confusing

### ISSUE THREAD

**Issue by MikeBazMSFT** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#98]
## Location

- Course: 203-03
- Exercise: 3
- Task: 1
- Step[s]: 1

## Description

The complete repository includes both a starter solution and a completed solution.  This is very helpful from a "I screwed up and don't know how to fix it" viewpoint, but calling the folder holding the finished version "solution" can be slightly confusing given the overloaded meaning of that word.  I realize that the lab instructions directly say to use "Starter" but I had multiple students this week not pick that up.  I suggest changing the name of the "Solution" folder to something that is not an overloaded term.  Maybe "EndOfLabCode" or something?  Something that is even less likely to be accidentally opened.

## Repro steps

n/a

**Comment by seesharprun** [comment]
I would recommend bringing this up in the MCT support forums. The folder names **Starter** and **Solution** have been in standard use for developer courses for years now and it is not a change that we can make independently in this course.
