### ISSUE TITLE
Answer key for Lab 4 has some incorrect using's

### ISSUE THREAD

**Issue by MikeBazMSFT** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#99]
## Location

- Course: 203L04
- Exercise: 4
- Task: 5
- Step[s]: 2

## Description

The Answer Key for Lab 4 (and just the Answer Key, not the non-AK) has some code references that are "using Microsoft.Azure.Storage..." when they should be "using Azure.Storage" instead.  Interestingly, before task 5, it's correct.

## Repro steps

n/a

**Comment by seesharprun** [comment]
You are correct. Exercise 4 Task 5 was deleted from the Lab instructions but not from the Lab Answer Key. Thanks for bringing that to our attention. It has been fixed in the online instructions.
